# Generated by Django 3.2.15 on 2022-09-08 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flotante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variableF1', models.FloatField()),
                ('variableF2', models.FloatField()),
                ('variableF3', models.FloatField()),
            ],
        ),
    ]
