# Generated by Django 3.2.15 on 2022-09-08 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prueba1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flotante',
            name='variableFSum',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='flotante',
            name='variableF1',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='flotante',
            name='variableF2',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='flotante',
            name='variableF3',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
