# Generated by Django 3.2.15 on 2022-09-08 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prueba1', '0002_auto_20220908_1000'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flotante',
            old_name='variableFSum',
            new_name='variableFSuma',
        ),
    ]
