# Generated by Django 3.2.15 on 2022-09-08 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prueba2', '0003_auto_20220907_2156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entero',
            name='variableE1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='entero',
            name='variableE2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='entero',
            name='variableE3',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
