# Generated by Django 3.2.15 on 2022-09-10 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prueba2', '0004_auto_20220908_1000'),
    ]

    operations = [
        migrations.AddField(
            model_name='entero',
            name='variableESuma',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
