# Generated by Django 3.2.15 on 2022-10-09 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Datos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('var1', models.IntegerField(blank=True, null=True)),
                ('var2', models.CharField(max_length=1)),
                ('var3', models.IntegerField(blank=True, null=True)),
                ('var4', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
