# Generated by Django 3.2.15 on 2022-10-09 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datosBase', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Datos',
            new_name='Dato',
        ),
    ]
